### ISSUE TITLE
Proper way to create Principals?

### ISSUE THREAD

**Issue by JacobWeyer** [Optum/dce#292]
**Version information**
DCE v0.27

**Describe the bug**
Whenever I create an account 
`dce leases create -b 300 -c USD -e my.email@email.com -E 2w -p DCEPrincipal`

The first creates fine, the second then fails. If I try to special an arn in the principal it ends up not being associated with the correct account? I created 10 child accounts with Terraform with the same principal role name. 

Is there a proper way to set principals? 

**To Reproduce**
Run the dce leases command above twice in a row and it will throw a postLeasesConflict error

**Expected behavior**
It to lease two separate accounts

**Additional context**
Looking more for clarification on the proper way to handle this with DCE

**Comment by marinatedpork** [comment]
Hi @JacobWeyer ,

The value of the `-p` argument should be the unique ID of the user to which the lease belongs – not the name of the DCE IAM role as it looks like you're providing in your example. So, when you provide `DCEPrincipal` as the value of the `-p` argument, it works the first time because you're effectively saying `DCEPrincipal` is the owner of the lease. It fails the second time because the "user" (`DCEPrincipal`) already has an `Active` lease, and users can only have one `Active` lease at a time.

If you run the create command with the `-h` flag, you'll see the documentation for the create lease command:

```
dce leases create -h
=> Create a lease.

Usage:
  dce leases create [flags]

Flags:
  -b, --budget-amount float      The leased accounts budget amount
  -c, --budget-currency string   The leased accounts budget currency (default "USD")
  -e, --email stringArray        The email address that budget notifications will be sent to
  -h, --help                     help for create
  -p, --principal-id string      Principle ID for the user of the leased account

Global Flags:
      --config string   config file (default "redacted/.dce.yaml")
```

Note the following:

```
-p, --principal-id string      Principle ID for the user of the leased account
```

Your issue, though, might indicate that we could be better in defining our terminology both in the CLI as well as the DCE documentation.

**Comment by JacobWeyer** [comment]
Just to clarify, it's expecting an existing IAM User from another account as the Principal? 

I guess we're implementing DCE a bit differently with our SSO and so it's probably not a useful value for what we're doing. 

also, small text bug: `--principal-id string      Principle ID`

**Comment by marinatedpork** [comment]
@JacobWeyer - how you implement users is up to you, so the principal ID is not _necessarily_ an existing IAM user. This value should be an identifier of an existing user in your organization and must be unique among users (e.g. company email). DCE _does_ support Amazon Cognito user pools if you need to implement users. Otherwise, if your organization has its own user implementation then you can put those unique identifiers in the `principal-id` parameter.

RE: spelling error - Good call, thanks for finding that.

**Comment by JacobWeyer** [comment]
Thanks for the quick response. It makes more sense to me now.

Another question, not sure if it should be its own topic, but if we try to create an account with the expiration of 1 hour, it seems to change to 1 week. Should this be its own issue or is this intended? I don't want to clutter up the workflow and I'm working on updating some of docs with my findings as a PR soon.

**Comment by marinatedpork** [comment]
@JacobWeyer - no worries. You're definitely not cluttering up the workflow, and we very much appreciate your questions.

If you're creating a lease directly via the API and experience incorrect behavior with expiration date, please make a new issue here. If you're creating it via the CLI, the please make an issue in the [DCE CLI](https://github.com/Optum/dce-cli) repo. Thanks

With regards to this issue, there does not appear to be anything to resolve with creating principals so I am going to go ahead and close this issue. Thanks
